### ISSUE TITLE
openstack-full: unable to use sudo on Debian "sudo: unable to resolve host"

### ISSUE THREAD

**Issue by goldyfruit** [redhat-cip/edeploy-roles#83]
On Debian, we have to add "127.0.1.1 theservername" in /etc/hosts to be able to use sudo.
If this line is not in /etc/hosts, the error appears : 

```
sudo: unable to resolve host
```

**Comment by goneri** [comment]
Hi,

This issue is open since September. Can we close it?

**Comment by goneri** [comment]
🎉
