### ISSUE TITLE
openstack-full default user in mysql : 'root'@'os-ci-edeploy.XXX.com';

### ISSUE THREAD

**Issue by gaelL** [redhat-cip/edeploy-roles#92]
After deploying new host with openstack-full role, we have a mysql user remaining from the host used to build the role I think.

`'root'@'os-ci-edeploy.XXX.com'; (XXX beacause i don't know if this domain is public)`

**Comment by goneri** [comment]
hi @gaelL,

Is the issue fixed for you? Is so, can we close the issue?

**Comment by goneri** [comment]
Thanks @gaelL ^^
